# Generated by Django 5.1.6 on 2025-03-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
