# Generated by Django 5.1.7 on 2025-04-10 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='leave_payment',
            field=models.DecimalField(
                blank=True, 
                decimal_places=2, 
                max_digits=10, 
                null=True, 
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ] 