# Generated by Django 5.1.7 on 2025-04-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_salary_leave_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('CEO', 'CEO Report'), ('EMPLOYEE', 'Employee Report')], max_length=10)),
                ('file_path', models.CharField(max_length=255)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
            ],
        ),
    ]
